query fetchDraws($type: String!, $date: String!) {
  draw(type: $type, date: $date) {
    draws {
      date
      numbers
      jackpot
      additionalNumbers
      odds {
        numberOfWinners
        odd
        winningClass
      }
    }
  }
}
